### ISSUE TITLE
Step 19 Error of Malformed auth code.

### ISSUE THREAD

**Issue by dark-ryuk** [ShuvamJaswal/Gdrive-Stremio-Update#16]
![Screenshot 2024-02-01 195034](https://github.com/ShuvamJaswal/Gdrive-Stremio-Update/assets/115157680/1cf0aa8f-d5f5-4441-b84f-e8379c8b3326)
Getting an error in Method 1, when entering the authorization code, Any Solutions??

**Comment by High-rider** [comment]
> ![Screenshot 2024-02-01 195034](https://private-user-images.githubusercontent.com/115157680/301534827-1cf0aa8f-d5f5-4441-b84f-e8379c8b3326.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODI1NDUsIm5iZiI6MTcxNDI4MjI0NSwicGF0aCI6Ii8xMTUxNTc2ODAvMzAxNTM0ODI3LTFjZjBhYThmLWQ1ZjUtNDQ0MS1iODRmLWU4Mzc5YzhiMzMyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQwNTMwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGU3YjcyOWNiZmVhMGM0ZmE1ZWMzNzAxY2FmYzE2OTZhNzUwZDVkN2I1YzY1OGZjOWM1ZTc5MDQ2OTFiYjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xIOv0GjIwh9B4t_TdgP9MJuLLEdApC-qnDrLg-X3mBc) Getting an error in Method 1, when entering the authorization code, Any Solutions??

I am having the same error, have you found any solution?
