### ISSUE TITLE
it shows serverless function has crashed and error while installing addon

### ISSUE THREAD

**Issue by vb036** [ShuvamJaswal/Gdrive-Stremio-Update#2]
![1673033139511430387343977418390](https://user-images.githubusercontent.com/121882780/211084961-a0f6a63a-4cb1-4a91-9bde-1ffb43c5ac52.jpg)

**Comment by ShuvamJaswal** [comment]
@vb036  Did u follow steps 26 to 28?

**Comment by vb036** [comment]
i had not copied the correct token string its working now. Thanks mate
