### ISSUE TITLE
Filtering issue

### ISSUE THREAD

**Issue by mg8297819** [ShuvamJaswal/Gdrive-Stremio-Update#3]
Shows another tv show from another year or just having the keyword.

![Screenshot_20230112_212259_Stremio](https://user-images.githubusercontent.com/79903502/212078315-6bd0afda-52f9-449d-b465-0b1b7e6cbd64.jpg)

**Comment by ShuvamJaswal** [comment]
You are searching 

Island season 1 episode 4

According to that it will display all the files in your drive whose name CONTAIN these words. There's not much we can do only ways to fix this are
1. We add episode year during search but usually series uploaded on gdrive don't have year in the name.

2. We know the exact name of file to search which isn't possible either.


If u want 
The search query is generated by
Line 29
Line 37-41 
In file sgd/gdrive.py

P.S: care sharing that TD?

**Comment by mg8297819** [comment]
> P.S: care sharing that TD?

Check your reddit
