### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by bittoo25b** [ShuvamJaswal/Gdrive-Stremio-Update#6]
unable to deploy repo serverless error

**Comment by ShuvamJaswal** [comment]
> unable to deploy repo serverless error

Can u show error log?

**Comment by bittoo25b** [comment]
i showed this to my frnd who works on python but we aint came up to solution

**Comment by bittoo25b** [comment]
ohk let me try as im not IT guy ...checking

**Comment by ShuvamJaswal** [comment]
Text me on telegram @ShuvamTheBeast

**Comment by bittoo25b** [comment]
i have texted u there

**Comment by pcgamer404** [comment]
I am having a similar problem it showing "This Serverless Function has crashed"

**Comment by NishantMajumdar** [comment]
Bump

**Comment by barnoii** [comment]
Any updates on this?
