### ISSUE TITLE
Could someone confirm if the addon is working on v1.5.8 Android TV

### ISSUE THREAD

**Issue by AlyafeiAli** [ShuvamJaswal/Gdrive-Stremio-Update#8]
Hi there!  

Ever since updating Stremio to v1.5.8 and this addon stopped working.  
I created an issue [here](https://github.com/ssnjr2002/stremio-gdrive/issues/37#issue-1740257424) and [here](https://github.com/Stremio/stremio-bugs/issues/465#issue-1740282544), but I don't see anyone complaining besides myself, so could someone please confirm whether this addon works for them on v1.5.8 Android TV or not?  
I tried the addon on a Shield TV and a CCwGTV.

Thank you

**Comment by Learner00100** [comment]
@ShuvamJaswal yes facing same issue.
Especially in new android tv app update of v1. 5.8

**Comment by AlyafeiAli** [comment]
Issue has been fixed in v1.5.11.
